import {
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from 'constants/navigation.constant'

import { ADMIN, ROOT, OPERATORE } from '../../constants/roles.constant'

const navigationConfig = [
    {
        key: 'home',
        path: '/home',
        title: 'Home',
        translateKey: 'nav.home',
        icon: 'link',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN,OPERATORE,ROOT],
        subMenu: []
    },
    {
        key: 'tracking',
        path: '',
        title: 'Spedizioni',
        translateKey: 'nav.tracking',
        icon: 'monitor',
        colore: 'text-sky-500',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN,OPERATORE,ROOT],
        subMenu: [         
            {
                key: 'tracking.spedizioni',
                path: '/tracking/spedizioni',
                title: 'Spedizioni attive',
                translateKey: 'nav.tracking.spedizioni',
                icon: '',
                colore: 'text-red-500',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN,OPERATORE,ROOT],
                subMenu: [],
            }, 
            {
                key: 'tracking.archivio',
                path: '/tracking/archivio',
                title: 'Spedizioni archiviate',
                translateKey: 'nav.tracking.archivio',
                icon: '',
                colore: 'text-red-500',
                stato: 'ATTIVO',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN,OPERATORE,ROOT],
                subMenu: [],
            },
            {
                key: 'tracking.update',
                path: '/tracking/aggiorna-spedizioni',
                title: 'Aggiorna spedizioni',
                translateKey: 'nav.tracking.update',
                icon: '',
                colore: 'text-red-500',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN,OPERATORE,ROOT],
                subMenu: [],
            },                        
        ],
    },    
    {
        key: 'crm',
        path: '',
        title: 'Crm',
        translateKey: 'nav.crm',
        icon: 'crm',
        colore: 'text-sky-500',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN,OPERATORE,ROOT],
        subMenu: [
            {
                key: 'crm.clienti',
                path: '/crm/clienti/',
                title: 'Clienti',
                translateKey: 'nav.crm.clienti',
                icon: '',
                colore: 'text-red-500',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN,OPERATORE,ROOT],
                subMenu: [],
            },
            {
                key: 'crm.listini',
                path: '/crm/listini/',
                title: 'Listini',
                translateKey: 'nav.crm.listini',
                icon: '',
                colore: 'text-red-500',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN,OPERATORE,ROOT],
                subMenu: [],
            },
                                                                                                
        ],
    },
    {
        key: 'logistica',
        path: '',
        title: 'Logistica',
        translateKey: 'nav.logistica',
        icon: 'admin',
        colore: 'text-sky-500',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN,OPERATORE,ROOT],
        subMenu: [
            {
                key: 'logistica.corrieri',
                path: '/logistica/corrieri/',
                title: 'Corrieri',
                translateKey: 'nav.logistica.corrieri',
                icon: '',
                colore: 'text-red-500',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN,OPERATORE,ROOT],
                subMenu: [],
            },                                             
        ],
    },    
    {
        key: 'sistema',
        path: '',
        title: 'Sistema',
        translateKey: 'nav.sistema',
        icon: 'setup',
        colore: 'text-sky-500',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN,OPERATORE,ROOT],
        subMenu: [         
            {
                key: 'sistema.account',
                path: '/sistema/account/',
                title: 'Account',
                translateKey: 'nav.sistema.account',
                icon: '',
                colore: 'text-red-500',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN,OPERATORE,ROOT],
                subMenu: [],
            },
            {
                key: 'sistema.operatori',
                path: '/sistema/operatori/',
                title: 'Operatori',
                translateKey: 'nav.sistema.operatori',
                icon: '',
                colore: 'text-red-500',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN,OPERATORE,ROOT],
                subMenu: [],
            },                                              
            {
                key: 'sistema.tabelle',
                path: '/sistema/tabelle/',
                title: 'Tabelle di base',
                translateKey: 'nav.sistema.tabelle',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN,OPERATORE,ROOT],
                subMenu: [],
            },                          
        ],
    },

]

export default navigationConfig
